on: push
name: golang-ci
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: run
        uses: cedrickring/golang-action@1.5.2
        env:
          GO111MODULE: "on"